apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultx-backend
  namespace: vaultx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vaultx-backend
  template:
    metadata:
      labels:
        app: vaultx-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/hrushi4151/vaultx-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: vaultx-config
            - secretRef:
                name: vaultx-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: vaultx-backend-service
  namespace: vaultx
spec:
  selector:
    app: vaultx-backend
  ports:
    - port: 8080
      targetPort: 8080
