apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultx-config
  namespace: vaultx
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_URL: "jdbc:postgresql://postgres-service:5432/vaultx"
  FACE_SERVICE_URL: "http://vaultx-face-service:8002"
  OCR_SERVICE_URL: "http://vaultx-ocr-service:8003"
  DEDUP_SERVICE_URL: "http://vaultx-deduplication-service:8004"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://vaultx.local"

---
apiVersion: v1
kind: Secret
metadata:
  name: vaultx-secrets
  namespace: vaultx
type: Opaque
stringData:
  POSTGRES_DB: "vaultx"
  POSTGRES_USER: "vaultx_user"
  POSTGRES_PASSWORD: "vaultx_secure_password_123!"
  JWT_SECRET: "c2VjdXJlX3ZhdWx0eF9qd3Rfc2VjcmV0X2tleV9mb3JfZGVwbG95bWVudF8yMDI2"
