apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultx-face-service
  namespace: vaultx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vaultx-face-service
  template:
    metadata:
      labels:
        app: vaultx-face-service
    spec:
      containers:
        - name: face-service
          image: ghcr.io/hrushi4151/vaultx-face-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: vaultx-face-service
  namespace: vaultx
spec:
  selector:
    app: vaultx-face-service
  ports:
    - port: 8002
      targetPort: 8002
