package com.vaultx.service.impl;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import com.vaultx.service.PdfProcessingService;
import lombok.extern.slf4j.Slf4j;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.multipdf.PDFMergerUtility;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.encryption.AccessPermission;
import org.apache.pdfbox.pdmodel.encryption.StandardProtectionPolicy;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import org.apache.pdfbox.util.Matrix;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.time.LocalDate;
import java.util.List;

@Service
@Slf4j
public class PdfProcessingServiceImpl implements PdfProcessingService {

    @Override
    public void mergePdfs(List<InputStream> sources, OutputStream output) throws Exception {
        PDFMergerUtility merger = new PDFMergerUtility();
        merger.setDestinationStream(output);
        for (InputStream source : sources) {
            merger.addSource(new org.apache.pdfbox.io.RandomAccessReadBuffer(source));
        }
        merger.mergeDocuments(org.apache.pdfbox.io.IOUtils.createMemoryOnlyStreamCache());
    }

    @Override
    public void imagesToPdf(List<InputStream> imageSources, OutputStream output) throws Exception {
        try (PDDocument doc = new PDDocument()) {
            for (InputStream imgStream : imageSources) {
                byte[] imgBytes = imgStream.readAllBytes();
                PDImageXObject pdImage = PDImageXObject.createFromByteArray(doc, imgBytes, "image");
                
                // Create a page matching image dimensions
                PDPage page = new PDPage(new org.apache.pdfbox.pdmodel.common.PDRectangle(pdImage.getWidth(), pdImage.getHeight()));
                doc.addPage(page);
                
                try (PDPageContentStream contents = new PDPageContentStream(doc, page)) {
                    contents.drawImage(pdImage, 0, 0);
                }
            }
            doc.save(output);
        }
    }

    @Override
    public InputStream generateCoverPage(String title, String description, String ownerName, int documentCount) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Document document = new Document();
        PdfWriter.getInstance(document, baos);
        document.open();

        Font titleFont = new Font(Font.HELVETICA, 24, Font.BOLD);
        Font subtitleFont = new Font(Font.HELVETICA, 16, Font.NORMAL);
        Font bodyFont = new Font(Font.HELVETICA, 12, Font.NORMAL);

        document.add(new Paragraph("VaultX Secure Bundle", subtitleFont));
        document.add(new Paragraph(" "));
        document.add(new Paragraph(title, titleFont));
        document.add(new Paragraph(" "));
        
        if (description != null && !description.isEmpty()) {
            document.add(new Paragraph(description, bodyFont));
            document.add(new Paragraph(" "));
        }
        
        document.add(new Paragraph("Generated by: " + ownerName, bodyFont));
        document.add(new Paragraph("Date: " + LocalDate.now().toString(), bodyFont));
        document.add(new Paragraph("Total Documents: " + documentCount, bodyFont));

        document.close();
        return new ByteArrayInputStream(baos.toByteArray());
    }

    @Override
    public InputStream generateTableOfContents(List<String> documentTitles) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Document document = new Document();
        PdfWriter.getInstance(document, baos);
        document.open();

        Font titleFont = new Font(Font.HELVETICA, 18, Font.BOLD);
        Font bodyFont = new Font(Font.HELVETICA, 12, Font.NORMAL);

        document.add(new Paragraph("Table of Contents", titleFont));
        document.add(new Paragraph(" "));

        for (int i = 0; i < documentTitles.size(); i++) {
            document.add(new Paragraph((i + 1) + ". " + documentTitles.get(i), bodyFont));
        }

        document.close();
        return new ByteArrayInputStream(baos.toByteArray());
    }

    @Override
    public void addPageNumbers(InputStream source, OutputStream output, String position) throws Exception {
        try (PDDocument doc = Loader.loadPDF(source.readAllBytes())) {
            int totalPages = doc.getNumberOfPages();
            for (int i = 0; i < totalPages; i++) {
                PDPage page = doc.getPage(i);
                try (PDPageContentStream contentStream = new PDPageContentStream(doc, page, PDPageContentStream.AppendMode.APPEND, true, true)) {
                    contentStream.beginText();
                    contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 10);
                    
                    String text = "Page " + (i + 1) + " of " + totalPages;
                    // Position roughly at bottom center
                    float x = page.getMediaBox().getWidth() / 2 - 20;
                    float y = 20;
                    
                    contentStream.newLineAtOffset(x, y);
                    contentStream.showText(text);
                    contentStream.endText();
                }
            }
            doc.save(output);
        }
    }

    @Override
    public void addWatermark(InputStream source, OutputStream output, String text) throws Exception {
        try (PDDocument doc = Loader.loadPDF(source.readAllBytes())) {
            for (PDPage page : doc.getPages()) {
                float pageWidth = page.getMediaBox().getWidth();
                float pageHeight = page.getMediaBox().getHeight();

                try (PDPageContentStream contentStream = new PDPageContentStream(doc, page, PDPageContentStream.AppendMode.APPEND, true, true)) {
                    contentStream.beginText();
                    contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 45);
                    contentStream.setNonStrokingColor(180, 180, 180); // Darker visible light gray
                    
                    float x = pageWidth / 4f;
                    float y = pageHeight / 3f;
                    Matrix matrix = Matrix.getRotateInstance(Math.toRadians(35), x, y);
                    contentStream.setTextMatrix(matrix);
                    
                    contentStream.showText(text);
                    contentStream.endText();
                }
            }
            doc.save(output);
        }
    }

    @Override
    public void encryptPdf(InputStream source, OutputStream output, String ownerPwd, String userPwd, 
                           boolean allowPrint, boolean allowCopy, boolean allowEdit) throws Exception {
        try (PDDocument doc = Loader.loadPDF(source.readAllBytes())) {
            AccessPermission ap = new AccessPermission();
            ap.setCanPrint(allowPrint);
            ap.setCanExtractContent(allowCopy);
            ap.setCanModify(allowEdit);
            
            StandardProtectionPolicy spp = new StandardProtectionPolicy(ownerPwd, userPwd, ap);
            spp.setEncryptionKeyLength(128); // Standard 128 bit AES
            doc.protect(spp);
            doc.save(output);
        }
    }

    @Override
    public void addSignatureOverlay(InputStream source, OutputStream output, String imageBase64, String position) throws Exception {
        try (PDDocument doc = Loader.loadPDF(source.readAllBytes())) {
            String cleanBase64 = imageBase64;
            if (cleanBase64.contains(",")) {
                cleanBase64 = cleanBase64.substring(cleanBase64.indexOf(",") + 1);
            }
            byte[] imgBytes = java.util.Base64.getDecoder().decode(cleanBase64);
            PDImageXObject pdImage = PDImageXObject.createFromByteArray(doc, imgBytes, "signature");

            float targetWidth = 140; // Signature width in PDF points
            float targetHeight = (pdImage.getHeight() * targetWidth) / pdImage.getWidth();

            for (PDPage page : doc.getPages()) {
                float pageWidth = page.getMediaBox().getWidth();
                float pageHeight = page.getMediaBox().getHeight();

                float x = pageWidth - targetWidth - 30; // Default BOTTOM_RIGHT
                float y = 30;

                if (position != null && position.startsWith("CUSTOM:")) {
                    try {
                        String[] coords = position.substring(7).split(",");
                        float xPct = Float.parseFloat(coords[0]);
                        float yPct = Float.parseFloat(coords[1]);
                        x = (pageWidth * xPct / 100f) - (targetWidth / 2f);
                        y = pageHeight - (pageHeight * yPct / 100f) - (targetHeight / 2f);
                    } catch (Exception e) {
                        log.warn("Could not parse custom position coordinates: {}", position, e);
                    }
                } else if ("BOTTOM_LEFT".equalsIgnoreCase(position)) {
                    x = 30;
                    y = 30;
                } else if ("TOP_RIGHT".equalsIgnoreCase(position)) {
                    x = pageWidth - targetWidth - 30;
                    y = pageHeight - targetHeight - 30;
                } else if ("TOP_LEFT".equalsIgnoreCase(position)) {
                    x = 30;
                    y = pageHeight - targetHeight - 30;
                } else if ("CENTER".equalsIgnoreCase(position)) {
                    x = (pageWidth - targetWidth) / 2;
                    y = (pageHeight - targetHeight) / 2;
                }

                // Constrain within page boundaries
                x = Math.max(10, Math.min(pageWidth - targetWidth - 10, x));
                y = Math.max(10, Math.min(pageHeight - targetHeight - 10, y));

                try (PDPageContentStream contentStream = new PDPageContentStream(doc, page, PDPageContentStream.AppendMode.APPEND, true, true)) {
                    contentStream.drawImage(pdImage, x, y, targetWidth, targetHeight);
                }
            }
            doc.save(output);
        }
    }

    @Override
    public void extractPages(InputStream source, List<Integer> pageNumbers, OutputStream output) throws Exception {
        try (PDDocument sourceDoc = Loader.loadPDF(source.readAllBytes());
             PDDocument newDoc = new PDDocument()) {
            int totalPages = sourceDoc.getNumberOfPages();
            for (Integer pageNum : pageNumbers) {
                if (pageNum != null && pageNum >= 1 && pageNum <= totalPages) {
                    newDoc.addPage(sourceDoc.getPage(pageNum - 1));
                }
            }
            newDoc.save(output);
        }
    }
}
